### ISSUE TITLE
Add Simulators

### ISSUE THREAD

**Issue by socketteer** [dair-ai/Prompt-Engineering-Guide#13]
Even though it's not directly about prompt programming, many people have told me that reading [Simulators](https://www.lesswrong.com/posts/vJFdjigzmcXMhNTsx/simulators) made them much more effective at prompt programming. So I suggest it to be added to the list of resources.

**Comment by omarsar** [comment]
Absolutely! I thought I added it but it wasn't there, it was a different post from Lesswrong. Thanks.
