### ISSUE TITLE
Contributor List

### ISSUE THREAD

**Issue by tanersekmen** [dair-ai/Prompt-Engineering-Guide#137]
Hi,

I contributed the repo but I can not see myself in the contributor list. Is this problem caused by me?

**Comment by omarsar** [comment]
Can you point to the PRs/changes you made so I can figure out what's going on?

**Comment by tanersekmen** [comment]
Hi,
This is my PR. If you have a chance, can you check?
PR: https://github.com/dair-ai/Prompt-Engineering-Guide/pull/106
@omarsar

**Comment by omarsar** [comment]
@tanersekmen I still can't figure out what happened. I can see that your translation was merged but very strange that you are not appearing in the contributor list. By any chance, did you change any settings in your GitHub. Have you checked if you appear in other repo's contributor lists?

**Comment by tanersekmen** [comment]
Hi,

When I check other repos that I contribute, I can see myself on the contributor list. 

E.g. -> https://github.com/DataTalksClub/awesome-data-podcasts/graphs/contributors
other one -> https://github.com/f/awesome-chatgpt-prompts/graphs/contributors
In addition, you can check https://prompts.chat/ at the bottom of the page.
