### ISSUE TITLE
Discord link seems expired on the website.

### ISSUE THREAD

**Issue by parK-dev** [dair-ai/Prompt-Engineering-Guide#218]
This link leads to the following on discord -> https://discord.gg/FUyz9vPAwf

<img width="499" alt="Screenshot 2023-06-28 at 14 41 46" src="https://github.com/dair-ai/Prompt-Engineering-Guide/assets/77372584/e4a52b3c-c0dd-454e-a577-7ae668b304c7">

**Comment by elvinagam** [comment]
Try invite on readme file now. #286
