### ISSUE TITLE
Feedback for “Retrieval Augmented Generation (RAG)”

### ISSUE THREAD

**Issue by jannikjw** [dair-ai/Prompt-Engineering-Guide#224]
> You can find a [simple example of how to use retrievers and LLMs for question answering with sources(opens in a new tab)](https://python.langchain.com/en/latest/modules/chains/index_examples/vector_db_qa_with_sources.html) from the LangChain documentation.

The link in the text above is out-of-date

**Comment by omarsar** [comment]
fixed! thanks
