### ISSUE TITLE
Looking for collaborators to build end-to-end tutorials

### ISSUE THREAD

**Issue by omarsar** [dair-ai/Prompt-Engineering-Guide#23]
Tag your name below if interested and I can provide you with more information. I will post a list of ideas here in the coming days and we can assign based on interest and experience. I will be putting together the final list and tasks by the end of this week. Thanks for all the interest so far. Please join our [Discord](https://discord.gg/SKgkVT8BGJ) and join the following channel: `pe-tutorials`

- ReAct
- Knowledge-Augmented Prompting
- Prompting tutorials with the tools listed in the guide
- ChatGPT examples, including failure cases

**Comment by JMRLudan** [comment]
@JMRLudan, Would love to help out on this

**Comment by eug** [comment]
Sure, count me in

**Comment by hinofafa** [comment]
@hinofafa Hi Elvis, would like to give help on it. I am working on prompt engineering tasks too.

**Comment by c-s-ale** [comment]
Would definitely be interested in helping out!

**Comment by JasperRoque** [comment]
Sure, i'd be interested ☺️, add me up on chatgroup

**Comment by InesFTL** [comment]
Hi @InesFTL here would gadly help ✋

**Comment by brianjking** [comment]
I'd be happy to help

**Comment by GitataY** [comment]
I'm interested in helping out

**Comment by junwatu** [comment]
@junwatu  yes, why not.

**Comment by Pratiksha29** [comment]
I would want to help, count me in.

**Comment by Karenzhang7717** [comment]
I am also interested!

**Comment by sunwoongc** [comment]
@sunwoongc I want to help, too! 😄

**Comment by emcor89** [comment]
I'm sure interested too

**Comment by Shiva953** [comment]
I'm interested!

**Comment by ngtrgiabao** [comment]
Hi, Would like to give help on it

**Comment by emcor89** [comment]
Hi
I am interested

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by silopolis** [comment]
@silopolis would gladly give a hand here after French translation :)

**Comment by taolicd** [comment]
I am interested. I don't have in-depth knowledge in LLMs but I can bring my expertise in writing tutorials. I am a tech writer with 20+ years experience in software documentation.
