### ISSUE TITLE
error: subprocess-exited-with-error       python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by gitfans5** [dair-ai/Prompt-Engineering-Guide#24]
How to fix the error below

"Collecting dotenv
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details."

when running "!pip install dotenv"? Thanks.

**Comment by omarsar** [comment]
Hi @gitfans5 I believe it should be `pip install python-dotenv`. Thanks for bringing this up. I added a clarification in the notebook.
