### ISSUE TITLE
Minor content error in the APE page

### ISSUE THREAD

**Issue by yingjil** [dair-ai/Prompt-Engineering-Guide#49]
The prompt "Let's work this out it a step by step to be sure we have the right answer." elicits chain-of-though reasoning and improves performance on the MultiArith and GSM8K benchmarks:
=> the prompt is wrong

**Comment by yingjil** [comment]
Should be: Let's work this out in a step by step way to be sure we have the right answer.

**Comment by omarsar** [comment]
Thanks for this catch.

**Comment by dr-nefardio3058** [comment]
Hi there, @yingjil ! We wanted to check in and see if the issue you reported earlier has been resolved. If it has, we would greatly appreciate it if you could take a moment to close the issue. It's super easy – just click the "Close Issue" button at the bottom of the issue page.

Keeping the issue tracker clean and tidy is important for the health of our codebase. With fewer issues to manage, we can focus on the ones that need our attention and ensure that our code remains maintainable in the long run. For example, it's easier to identify trends and common issues when there are fewer open issues, which can lead to more efficient bug fixing and better overall code quality.

Thanks so much for your help in keeping our repo organized and contributing! 😄
