### ISSUE TITLE
I want to contribute by translating the content into Chinese

### ISSUE THREAD

**Issue by liyun95** [dair-ai/Prompt-Engineering-Guide#56]
Hi there,

I'm interested in contributing to this project by translating the existing content into Chinese. I'm a native Chinese speaker and I'm fluent in English, so I believe I can help make the content more accessible to a wider audience.

I'm a technical writer with years of experience in the IT field, so I have the confidence that I can manage it.

Please let me know if this is something you would be interested in. I'm happy to answer any questions you may have.

Thank you!

**Comment by LINGLONGQIAN** [comment]
> Hi there,
> 
> I'm interested in contributing to this project by translating the existing content into Chinese. I'm a native Chinese speaker and I'm fluent in English, so I believe I can help make the content more accessible to a wider audience.
> 
> I'm a technical writer with years of experience in the IT field, so I have the confidence that I can manage it.
> 
> Please let me know if this is something you would be interested in. I'm happy to answer any questions you may have.
> 
> Thank you!

I can do it together with you if possible.

**Comment by 5454245** [comment]
你们加油，我第二语言非英语的就不参合了，等你们的出来，我去找你们学习

**Comment by maximum80** [comment]
Hi there,
It was really exciting for me to read this guide!
I would like to contribute this project as translating current contents to Japanese for spreading this out to Japanese people.
So I also want to know how to contribute it.

Thanks.

**Comment by ZhangZeroHoo** [comment]
期待，坐等，加油！

**Comment by omarsar** [comment]
Hi @liyun95, @sntxerror, and others interested. 
The best way to do this right now is to directly submit a PR to the repo. 
You can create a folder for example `zh-pages` or `jp-pages` on the root of the repo and directly translate each `.mdx` file while preserving the folder structure of the original `pages` folder. I will then make the necessary changes to the web app to enable translation on the website. Please ignore the `guides` folder for now as it is highly like that we will deprecate content there. The most up-to-date information is in the `pages` folder and that's what we are using on the website (promptingguide.ai). 

Let me know if there is any way I can help further.
If you are translating in a language please let us know here and create a separate issue so we are able to manage it properly and no duplicate efforts.

**Comment by omarsar** [comment]
Hey all! The website now supports [中文](https://www.promptingguide.ai/zh) and [English](https://www.promptingguide.ai/). Welcoming more translations. 

Translating content is very simple. You can check out the `pages` folder for the file structure you need to follow. It's just adding `<file>.<language>.json` or `<file>.<language>.mdx` in the necessary folders. 

Reach out to me directly on [Discord](https://discord.gg/SKgkVT8BGJ) if you are interested to translate into another language and we can coordinate.

**Comment by liyun95** [comment]
> Hey all! The website now supports [中文](https://www.promptingguide.ai/zh) and [English](https://www.promptingguide.ai/). Welcoming more translations.
> 
> Translating content is very simple. You can check out the `pages` folder for the file structure you need to follow. It's just adding `<file>.<language>.json` or `<file>.<language>.mdx` in the necessary folders.
> 
> Reach out to me directly on [Discord](https://discord.gg/SKgkVT8BGJ) if you are interested to translate into another language and we can coordinate.

Hey, I guess it would be more efficient for translation if you could integrate this repo with Crowdin, which is an open source translation platform for streamlining localization management. Many open source projects use this tool to simplify translation contribution. You can check it out for more details: https://support.crowdin.com/github-integration/?q=github

**Comment by omarsar** [comment]
@liyun95 I have no experience with this but I will take a look.
