### ISSUE TITLE
Bad link in /about page

### ISSUE THREAD

**Issue by doggy8088** [dair-ai/Prompt-Engineering-Guide#63]
https://www.promptingguide.ai/about

![image](https://user-images.githubusercontent.com/88981/227426968-798f6afb-c0cb-4904-9e3b-0421602001fc.png)

This link to https://github.com/dair-ai/Prompt-Engineering-Guide/blob/main/LICENSE which is wrong. The right one should be https://github.com/dair-ai/Prompt-Engineering-Guide/blob/main/LICENSE.md

**Comment by omarsar** [comment]
Thanks for reporting this. I will fix it in the next PR.
