### ISSUE TITLE
Feedback for “Generated Knowledge Prompting”

### ISSUE THREAD

**Issue by lxm1117** [dair-ai/Prompt-Engineering-Guide#71]
Hi the text in the QA sections have some format issues. The text is not wrapped, so there is unseen text to the right edge. This has been the case for all previous web pages. I am using Brave browser on a MacBook Pro.

**Comment by omarsar** [comment]
Hi @lxm1117 can you please provide screenshots so I have a good idea what I need to fix. Thanks
