### ISSUE TITLE
Feedback for “GPT-4”

### ISSUE THREAD

**Issue by MaybeRichard** [dair-ai/Prompt-Engineering-Guide#78]
Hi, I want to contribute the prompt course by translating it into Chinese, how should I do that?

**Comment by hamzamoon** [comment]
By creating an AI model to translate the course in chinese language

**Comment by omarsar** [comment]
Hi @MaybeRichard, we have the Chinese translation already but it would be nice if you can review the current translation and perhaps update what needs to be updated through a PR. https://www.promptingguide.ai/zh

**Comment by MaybeRichard** [comment]
> Hi @MaybeRichard, we have the Chinese translation already but it would be nice if you can review the current translation and perhaps update what needs to be updated through a PR. https://www.promptingguide.ai/zh

Got it. Thanks and I'ii try to review the vurrent version.
