### ISSUE TITLE
Suggestion: white-space: pre-wrap on prompt examples

### ISSUE THREAD

**Issue by simonw** [dair-ai/Prompt-Engineering-Guide#87]
https://www.promptingguide.ai/introduction/examples currently looks like this for me:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/9599/229929276-35cf5462-5d73-4d9c-b67f-55666f0a4aed.png">

Adding `pre { white-space: pre-wrap; }` to the CSS causes it to look like this instead, which I think is much more useful:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/9599/229929181-8bc8f6db-8fca-4324-aeac-0cba583bbc55.png">

**Comment by simonw** [comment]
It would be great if there were little "copy" buttons on the prompts too, to help copy them to a clipboard.

I have those in my documentation here:

https://sqlite-utils.datasette.io/en/stable/reference.html

![CleanShot 2023-04-04 at 14 43 52@2x](https://user-images.githubusercontent.com/9599/229929542-a7604187-58a4-4378-ab0f-a6a63ed5e5a2.png)

Here's one way to implement those: https://til.simonwillison.net/javascript/copy-button

**Comment by omarsar** [comment]
Thanks, @simonw. This is very useful feedback. Will look into these very soon.
