### ISSUE TITLE
Spanish traslation

### ISSUE THREAD

**Issue by Puntua** [dair-ai/Prompt-Engineering-Guide#88]

**Comment by dr-nefardio3058** [comment]
Hi @Puntua ! Thank you for opening this issue and contributing to this repository. However, it seems like the issue you've opened is a bit incomplete. Could you tell us a bit more about what you're trying to address so we can better understand your concerns?

It is important to keep in mind that having incomplete issues can cause significant problems in a workflow. Such issues can lead to confusion, delays, and mistakes in the project's development. Therefore, it is crucial to provide as much detail as possible when opening an issue to avoid these complications.

That said, I would be happy to help you with your issue once you provide me with more information.

**Comment by omarsar** [comment]
@Puntua Thanks for your interest in helping with translation. To translate the content into Spanish, you can simply create a `es-pages` folder in the root. You can then translate all the `<>.en.mdx` files found in the pages folder and make sure to keep the same folder structure in your `es-pages` folder. In other words, don't touch the pages folder since your translated files will all be in the `es-pages` folder. Once you finish with the translations, you can submit PR and I will take care of integrating it into the website. Does this work for you?

I suggest also using a grammar tool that works for your language to make sure grammar is consistent and avoid spelling errors in your translations. Looking forward to your contributions and thanks a lot. Let me know if you have any questions.

**Comment by Puntua** [comment]
> _No description provided._

I would like to contribute to translating this repo into Spanish
I don't have a lot of experience working like this but I hope to gradually achieve it.

**Comment by omarsar** [comment]
Are you able to submit PR so I can inspect it?

**Comment by dr-nefardio3058** [comment]
@Puntua remember to create a pull request o we can review it!

**Comment by Puntua** [comment]
@dr-nefardio3058 how can I create a Pull request? (i guess its PR that @omarsar says)

**Comment by dr-nefardio3058** [comment]
Hi bro! To create a pull request you will need to clone the repository to your computer, the open it in your preferred code editor, create another branch, do changes, commit them and then create a pull request, when the PR is done, go back to main branch.

I suggest you to see a tutorial.

**Comment by Puntua** [comment]
ok. I´ll see a tutorial during this days. thank you

**Comment by fer-aguirre** [comment]
> 

Hola @Puntua! Yo también quiero hacer una traducción de la guía en español. Qué te parece si unimos fuerzas? También puedo ayudar con el tema del PR.

**Comment by Puntua** [comment]
> > 
> 
> 
> 
> Hola @Puntua! Yo también quiero hacer una traducción de la guía en español. Qué te parece si unimos fuerzas? También puedo ayudar con el tema del PR.

Genial Fer. Hice fork y clone el repositorio q lo tengo ya descargado. Si quieres vete diciendome. Prefieres por mail?

**Comment by dr-nefardio3058** [comment]
yo me uno bros envien email tambien a mi : kkigordaxo0@gmail.com

**Comment by nicksalazar** [comment]
Quiero unirme.

**Comment by Puntua** [comment]
Que bueno. Somos 4. Pasadme mail aniachat (at) proton.me y vemos como nos organizamos

**Comment by dr-nefardio3058** [comment]
sino hagamos discord

**Comment by nicksalazar** [comment]
https://discord.gg/cbRfsXDG
Aqui dejo el link discord.

**Comment by dr-nefardio3058** [comment]
ya me uni 😎

**Comment by Puntua** [comment]
I'm confused. There is no news on discord and I don't know if we are moving forward or not. Can someone tell me?

**Comment by omarsar** [comment]
Any updates here? I would suggest just one person try to translate if that works better. Any takers?

**Comment by aitor** [comment]
@omarsar I'll open a PR today for this.

**Comment by nicksalazar** [comment]
Hello friends, I am in charge of the translation, I have already translated 70% of the files.

**Comment by Puntua** [comment]
The idea was work together. Nicky how can we see files to read and correct?

**Comment by nicksalazar** [comment]
Amigos aquí dejo el PR, falta traducir algunos archivos, necesito su ayuda.

https://github.com/dair-ai/Prompt-Engineering-Guide/pull/127

**Comment by omarsar** [comment]
Hi everyone, I will be merging @nicksalazar PR over the weekend. Spanish translation is in huge demand and I want to make sure we can have it ready by the weekend if possible. Please free to check out his PR #127 and contribute to it before I review/merge it this weekend. Thanks, everyone.

**Comment by aitor** [comment]
@omarsar Please, review #128 too connected with the Spanish translation.

**Comment by omarsar** [comment]
Closing this issue as I am favoring the more complete translation by @aitor. There was a lot of confusion about efforts for this particular translation. I apologize if it caused any inconvenience. There is always a need for translations since I am constantly updating the English content.
